### ISSUE TITLE
Morning Session Final Code Review

### ISSUE THREAD

**Issue by samwel-mongare** [AmaduKamara/seafoods-app#33]
### Suggestions and Project highlights

-  Good job @AmaduKamara and @Debas-31 👏 
- Amazing implementation of the design and responsiveness.
- Nice code structure and documentation 🔥 

### Suggestions
- Check alignment of the comments buttons on smaller screens.

**Comment by AmaduKamara** [comment]
Thank you so much, bro. We'll fix all your suggestions. You guys have been very helpful in your reviews. Thanks once again for making our app better.
